updates
xenonca/ptime pull request #5
Opened 2021-08-06 20:40 UTC by wsor4035

this pull request does the following
* adds luacheck
* adds github actions with luacheck
* removes code duplication
* removes pointless dependency on default
* removes/updates depreciated api calls
* refactors the code

2021-08-10 19:30 UTC, xenonca commented
I am not yet really familiar with GitHub Actions and luacheck, as soon as I've figured this out I'll check and merge this very much needed update

2021-08-10 22:45 UTC, wsor4035 commented
> I am not yet really familiar with GitHub Actions and luacheck, as soon as I've figured this out I'll check and merge this very much needed update

luacheck checks your code for accidental use of globals, line length limit, unused variables, etc. the included GitHub action simple runs luacheck on each commit and adds green checkmark or red x depending on the status 
![image](https://user-images.githubusercontent.com/24964441/128944313-71bf6e80-d60a-413e-a714-17dd537dc552.png)
you can find reports by clicking details on routine, example: https://github.com/wsor4035/ptime/runs/3265831640
![image](https://user-images.githubusercontent.com/24964441/128944367-619ff66d-92e6-4f5c-9802-447a6268ccef.png)

2021-08-16 19:02 UTC, xenonca requested changes

2021-08-16 19:02 UTC, xenonca commented on README.md
> +Code: MIT (https://opensource.org/licenses/MIT)
```suggestion
Code: [MIT](https://opensource.org/licenses/MIT) by xenonca, AnyZeeAreOkay, wsor4035
```

2021-08-16 19:02 UTC, xenonca commented on README.md
> +    xenonca
```suggestion
```

2021-08-16 19:02 UTC, xenonca commented on README.md
> +    AnyZeeAreOkay
```suggestion
```

2021-08-16 19:02 UTC, xenonca commented on README.md
> +    wsor4035
```suggestion
```

2021-08-16 19:02 UTC, xenonca commented on README.md
>  Media: MIT (https://opensource.org/licenses/MIT) by xenonca
```suggestion
Media: [MIT](https://opensource.org/licenses/MIT) by xenonca
```

2021-08-16 19:02 UTC, xenonca commented on README.md
> +v1.3
```suggestion
v1.3  
```

2021-08-17 22:50 UTC, wsor4035 commented
@xenonca resolved

2021-09-07 18:34 UTC, xenonca approved these changes

2021-09-07 18:38 UTC, merged